# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create a release image in chroot environment
        uses: pguyot/arm-runner-action@v2.5.1
        id: arm_runner_install
        with:
          image_additional_mb: 4096
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          optimize_image: yes
          commands: |
            # Disable IPv6 in case it is configured but does not work
            ping6 -c 1 www.ietf.org || sudo sysctl -w net.ipv6.conf.eth0.disable_ipv6=1
            sudo apt-get update -y --allow-releaseinfo-change
            sudo apt-get autoremove --purge -y
            sudo apt-get clean

      - name: Compress the release image
        run: |
          mv ${{ steps.arm_runner_install.outputs.image }} rpi.img
          sudo xz -T 0 -v rpi.img

      - name: Upload the image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi.img.xz
          path: rpi.img.xz
          if-no-files-found: error
          retention-days: 1

  create_release:
    name: Release
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Define the release name
        id: release_name
        run: |
          if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
             echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/tags\//}
          elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
             echo ::set-output name=RELEASE_NAME::releng
          else
             echo ::set-output name=RELEASE_NAME::${GITHUB_REF/refs\/heads\//}
          fi

      - name: Download the image artifacts
        uses: actions/download-artifact@v3.0.1

      - name: Create release with release image
        if: startsWith(github.ref, 'refs/tags/')
        uses: "marvinpinto/action-automatic-releases@v1.1.2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          title: Release
          files: rpi.img.xz
